### ISSUE TITLE
Abstraire le type d'export

### ISSUE THREAD

**Issue by ttben** [MarK9992/lmu-core#1]
Le but est d'avoir une abstraction au niveau de l'export (autre que AbstractWriter ?) afin d'offrir un second paramètre dans l'API de l'application.
L'utilisateur fournit à la fois ce qu'il veut analyser et le format de sortie.
Le format de sortie contient (?) également le chemin de sortie

**Comment by markarasev** [comment]
let's do this
https://www.youtube.com/watch?v=-N6sqdrJzVo#t=18s
