### ISSUE TITLE
Refactor renderer package

### ISSUE THREAD

**Issue by ttben** [MarK9992/lmu-core#4]
- [ ] Rename setModel method into generate
- [ ] Move detailWriter into another package (nothing to do here)
- [ ] Check why only ImageRenderer keeps IModel reference
- [ ] Add a factory that returns  the proper ClassDiagrammViewer implementation from a string description (usefull for plugin)

**Comment by markarasev** [comment]
I think this package is not necessary. It comes from the gui package, it is not used by the output package and its only link to the core is a dependence on the IModel class but the core doesn't depend on it.
